CREATE TABLE IF NOT EXISTS "wallet_bindings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "wallet_bindings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_address" text NOT NULL,
	"flowEDUAddress" text NOT NULL,
	"private_key" text NOT NULL,
	"signature" text,
	"message" text,
	"timestamp" bigint,
	"created_at" timestamp DEFAULT now()
);
