CREATE TYPE "public"."origin" AS ENUM('BSC', 'EDUChain', 'Arbitrum');--> statement-breakpoint
CREATE TYPE "public"."status" AS ENUM('pending', 'handled', 'ignored');--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "job_locks" (
	"job" text PRIMARY KEY NOT NULL,
	"locked_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "txs_on_arb" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "txs_on_arb_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"originHash" varchar(66),
	"valueRecipient" varchar(42) NOT NULL,
	"valueSender" varchar(42) NOT NULL,
	"arbHash" json DEFAULT '[]'::json,
	"value" numeric(78, 0) NOT NULL,
	"origin" "origin" NOT NULL,
	"status" "status" DEFAULT 'pending' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "txs_on_arb_originHash_unique" UNIQUE("originHash")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "txs_on_bsc" (
	"txHash" varchar(66) PRIMARY KEY NOT NULL,
	"valueSender" varchar(42) NOT NULL,
	"valueRecipient" varchar(42) NOT NULL,
	"ca" varchar(42),
	"value" numeric(78, 0) NOT NULL,
	"status" "status" DEFAULT 'pending',
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "txs_on_edu_chain" (
	"txHash" varchar(66) PRIMARY KEY NOT NULL,
	"valueSender" varchar(42) NOT NULL,
	"valueRecipient" varchar(42) NOT NULL,
	"ca" varchar(42),
	"value" numeric(78, 0) NOT NULL,
	"status" "status" DEFAULT 'pending',
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "wallet_bindings" ALTER COLUMN "message" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "wallet_bindings" ALTER COLUMN "timestamp" SET NOT NULL;